### ISSUE TITLE
Milestone 3, README files

### ISSUE THREAD

**Issue by DmytroLyt** [MIT-Emerging-Talent/2024-group-11-cdsp#56]
- [x] Make doc file to be user friendly
- [x] convert fields Data Fields into table
- [x] add hyperlinks to field Used Files
- [x] update Requirements
